kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-Deployment
  namespace: cloud-healing
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: frontend
  template:
    metadata:
      name: frontend-Deployment
      labels:
        apps: frontend
    spec:
      containers:
        - name: frontend
          image: <username>/frontend-Deployment
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: cloud-healing-config
                  key: VITE_API_URL
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "256m"
              memory: "512Mi"

      