kind: Secret
apiVersion: v1
metadata: 
  name: cloud-healing-Secret
  namespace: cloud-healing
type: Opaque
data:
  # please assure that all the api key should be in base 64 encoded formate 
  SUPABASE_KEY: your-supabase-anon-key
  GEMINI_API_KEY: your-api-key
  ANTHROPIC_API_KEY: your-anthropic-api-key
  OPENAI_API_KEY: your-open-api-key
  